# Generated by Django 3.0 on 2020-02-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
