# Generated by Django 2.2.7 on 2019-12-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
