# Generated by Django 2.2.7 on 2020-01-25 23:28

import bug.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=200)),
                ('bug_description', models.CharField(max_length=500)),
                ('bug_states', models.CharField(default='new', max_length=50)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=bug.models.get_image_filename, verbose_name='Image')),
                ('bug', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bug.Bug')),
            ],
        ),
    ]
