# Generated by Django 2.2.7 on 2019-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=200)),
                ('bug_description', models.CharField(max_length=500)),
                ('bug_status', models.BooleanField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
