# Generated by Django 2.2.7 on 2019-11-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='bug_status',
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_states',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
