# Generated by Django 3.0 on 2020-02-05 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='bug',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_image', to='bug.Bug'),
        ),
    ]
