# Generated by Django 3.0 on 2020-02-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_auto_20200205_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='bug_states',
            new_name='bug_status',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bug.Bug')),
            ],
        ),
    ]
