# Generated by Django 3.0 on 2020-02-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_auto_20200205_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
