# Generated by Django 2.2.7 on 2019-12-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='bug',
        ),
    ]
