# Generated by Django 3.0 on 2020-02-16 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0006_request_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='pub_date',
            field=models.DateTimeField(editable=False, verbose_name='date published'),
        ),
    ]
