# Generated by Django 3.0 on 2020-02-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0008_auto_20200217_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.CharField(default='Low', max_length=50),
        ),
    ]
