# Generated by Django 3.0 on 2020-02-17 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0009_bug_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
